config/routes.rb
Rails.application.routes.draw do
  root 'payments#index'
  post 'charge_customer' => 'payments#charge_customer', as: :charge_customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/payments_controller.rb
# encoding: utf-8
class PaymentsController < ApplicationController
  def index
  end

  def charge_customer
    if params[:card_token]
      request = Espago.clients(:post, card: params[:card_token], description: "New client" ).body
      puts "Creating client"
      puts request
      charge = {amount: 100.0, description: "Description", currency: 'pln', client: request["id"]}
      puts "Charging client"
      response = Espago.charges(:post, charge)      
      puts response.body
      redirect_to root_url
    else
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title EspagoIntegration
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = yield

app/views/payments/index.html.haml
%h1 Payments
=form_tag charge_customer_path, id: "espago_form" do
  .form-group
    %label Credit Card Number
    %input#espago_card_number{type: "text"}
    %span#espago_card_number_error
  %br
  .form-group
    %label First Name
    %input#espago_first_name{type: "text"}
    %span#espago_first_name_error
  %br
  .form-group
    %label Last Name
    %input#espago_last_name{type: "text"}
    %span#espago_last_name_error
  %br
  .form-group
    %label Month expire
    %input#espago_month{type: "text"}
    %span#espago_month_error
  %br
  .form-group
    %label Year expire
    %input#espago_year{type: "text"}
    %span#espago_year_error
  %br
  .form-group
    %label Verification Value
    %input#espago_verification_value{type: "text"}
    %span#espago_verification_value_error
  =submit_tag "Charge me"

:javascript
  $( document ).ready(function() {
    $("#espago_form").submit(function(event){
      var espago = new Espago({public_key: "#{Rails.application.secrets.espago_public_key}", custom: true, live: false});
      event.preventDefault();
      event.stopPropagation();
      if (espago.validate_card_number()){
        $("#espago_card_number_error").text("");
      } else {
        $("#espago_card_number_error").text("Data error!");
      };

      if (espago.validate_first_name()){
        $("#espago_first_name_error").text("");
      } else {
        $("#espago_first_name_error").text("Data error!");
      };

      if (espago.validate_last_name()){
        $("#espago_last_name_error").text("");
      } else {
        $("#espago_last_name_error").text("Data error!");
      };

      if (espago.validate_card_date()){
        $("#espago_year_error").text("");
      } else {
        $("#espago_year_error").text("Data error!");
      };

      if (espago.validate_card_cvc()){
        $("#espago_verification_value_error").text("");
      } else {
        $("#espago_verification_value_error").text("Data error!");
      };
      espago.create_token();
    });
  });